import type { ServerBuild } from '@remix-run/cloudflare';
import { createPagesFunctionHandler } from '@remix-run/cloudflare-pages';

export const onRequest: PagesFunction = async (context) => {
  // The server build is generated by `remix vite:build` and lives at
  // build/server in production. The typecheck runs before the build, so the
  // module is not present in dev and the import resolves to any. This is the
  // @remix-run pattern for Cloudflare Pages and the import is correct at
  // deploy time; we use ts-expect-error to acknowledge the dev-only gap.
  // @ts-expect-error build/server is generated by remix vite:build, not present at typecheck
  const serverBuild = (await import('../build/server')) as unknown as ServerBuild;

  const handler = createPagesFunctionHandler({
    build: serverBuild,
  });

  return handler(context);
};
